### ISSUE TITLE
protobufの構造

### ISSUE THREAD

**Issue by ras0q** [traPtitech/Emoine_R#66]
- ルートにあるapi/がpbの定義ファイル群であることが分かりにくい(自分で書いたくせにn敗してる)
- emoine_r/v1という構造を使ってるせいでgoに移した時のパッケージ名が終わってる
  - emoine_rv1connect
  - apiだしemoine/v2(v1?)でいいのでは
- markdownの場所
  - 深すぎるのでオプションがあれば浅い所に移す

**Comment by ras0q** [comment]
markdownはoptの最後を指定しなかったらdocs直下に作れるがファイル名が必須なため別protoパッケージを生やすと名前がコンフリクトしてエラーになる
それまでは指定なしでもいい気がする

```yaml
  - name: doc
    path:
      - go
      - run
      - github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
    out: ../../docs
    opt: markdown,protobuf.md,source_relative
```
